enum enunsqeefetivo {
    A = "Não - Aguardar Pagamento",
    C = "Não - Aguardar Pagamento",
    R = "Não - Aguardando documentos/relatório para efetuar Pagamento",
    D = "Não - Aguardando documentos/relatório para efetuar Pagamento",
    P = "Sim - Pagamento Efetuado",
    S = "Sim - Pagamento Efetuado",
    E = "Sim - Pagamento Efetuado",
    X = "Estorno",
    G = "Autorização Cancelamento pelo Financeiro",
    Y = "Cancelamento efetuado pelo Financeiro",
    Z = "Cancelamento efetuado pelo usuário",
    T = "Aguardando Transferência para saque",
    V = "Aguardando Transferência para Complemento",
    F = "Aguardando Transferência para Reembolso",
    B = "Aguardando Transferência para Complemento-Reembolso",
    K = "Aguaradando prestação de contas para transferência",
    N = "Transferência não autorizada",
    J = "SUSPENSO - Aguardar Transferência para saque",
    I = "SUSPENSO - Aguardar Transferência para Complemento",
    H = "SUSPENSO - Aguardar Transferência para Reembolso"  
  }