export const sqls = {
  selecionaDocPContasGeral: `
      SELECT a.dir_id_codigo, A.SQE_ID_CODIGO, A.NDO_ID_CODIGO, A.PCO_ID_CODIGO, A.PES_ID_CODIGO,
             A.PES_PESSOA, A.NDO_ID_NUMERO, A.NDO_DATA, A.NDO_DTENTREGA, A.PES_NOME, A.CHAPA, A.NOME,
             A.CODIGO, A.DESCRICAO, A.VALORTOTAL, A.SQE_DTPREST, A.TDE_DESCRICAO, A.SQE_VLSAQUE,
             A.SQE_VLPREST, A.PCO_TIPO, A.PCO_TOTDOC, A.PRA_ID_CODIGO, A.SQE_EFETIVO, A.TDE_ID_CODIGO
      FROM Financeiro.V009_DocPrestGeral a
    `,
  selecionaTransfRec: `
      SELECT A.CHAPADESTINO, A.NOMEDESTINO, A.SETORDESTINO,
             A.CODDIR, A.DIRETORIADESTINO,
             a.itf_valor, A.ITF_JUSTIFICA, A.ITF_DATA, A.RRE_ID_CODIGO, A.ITF_ID_CODIGO,
             A.PRA_ID_CODIGO, A.CHAPAORIGEM, A.TDE_ID_CODIGO, A.TDE_DESCRICAO,
             B.Nome, C.DESCRICAO, d.itf_autorizado
      FROM Financeiro.V009_TransfRec2 A
      JOIN Rm.Pfunc B ON A.CHAPAORIGEM = B.CHAPA
      JOIN Rm.Psecao C ON B.Codsecao = C.Codigo
      JOIN Financeiro.S009_ITENSTRANSF D ON a.itf_id_codigo = d.itf_id_codigo
    `,
  selecionaBalancoFunc: `
      SELECT ITE_ID_CODIGO, rre_id_codigo, dir_id_codigo, tde_id_codigo, chapa, irr_valor_sol,
             irr_data_sol, irr_valor_conc, irr_data_conc, irr_valor_prest, irr_data_prest, irr_valor_aut,
             descricao, tde_descricao, nome, valorsaque, valorpres, vltransf, vlextorno,
             valortotrec, pra_id_codigo, diretoria, valorsaldo
      FROM Financeiro.V009_Balancofunc
    `,
  selecionaBalancoDiretoria: `
      SELECT RRE_ID_CODIGO, DIR_ID_CODIGO, TDE_ID_CODIGO, VALORSOLICITADO, VALORAUTORIZADO,
             VALORCONCEDIDO, VALORPRESTCONTA, VALORSAQUES, VALORESTORNO, VALORTRANSFERIDO,
             VALORECEBIDO, DESCRICAO, TDE_DESCRICAO, PRA_ID_CODIGO, VALORSALDO
      FROM Financeiro.V009_Balancodiretoria
    `,
  selecionaPrestPend3: `
      SELECT * 
      FROM Financeiro.V009_PrestPendente3
    `,
  selecionaBalancoSetor: `
      SELECT RRE_ID_CODIGO, DIR_ID_CODIGO, CODSECAO, DESCRICAO, TDE_ID_CODIGO, TDE_DESCRICAO,
             VALORSOLICITADO, VALORAUTORIZADO, valorconcedido, valorprestconta, valorsaques,
             VALORESTORNO, VALORTRANSFERIDO, VALORECEBIDO, DIRETORIA, PRA_ID_CODIGO, VALORSALDO
      FROM Financeiro.V009_Balancosetor
    `,
  selecionaExtratoFunc2: `
      SELECT A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.TDE_ID_CODIGO, A.CHAPA,
             A.IRR_VALOR_SOL, A.IRR_DATA_SOL, A.IRR_VALOR_CONC, A.IRR_DATA_CONC,
             A.IRR_VALOR_PREST, A.IRR_DATA_PREST, A.IRR_VALOR_AUT, A.DESCRICAO, A.TDE_DESCRICAO,
             A.NOME, A.VALORTOTREC, A.VALORSAQUE, A.VALORPRES, A.VLTRANSF, A.VLEXTORNO, A.PRA_ID_CODIGO
      FROM Financeiro.v009_ExtratoFunc2 A
    `,
  selecionaSolPendNivel1: `
      SELECT A.DIR_ID_CODIGO, C.CODIGO, C.DESCRICAO,
             D.RRE_ID_CODIGO, D.PRA_ID_CODIGO
      FROM Comum.S000_Subordina1 A
      JOIN Rm.Psecao C ON A.Codigo = C.codigo
      JOIN Financeiro.S009_Reqrecursos D ON A.dir_id_codigo = D.dir_id_codigo
    `,
  selecionaSolPendNivel2: `
      SELECT A.DIR_ID_CODIGO, A.SB1_ID_CODIGO, C.CODIGO, C.DESCRICAO,
             D.RRE_ID_CODIGO, D.PRA_ID_CODIGO
      FROM Comum.S000_Subordina2 A
      JOIN Rm.Psecao C ON A.Codigo = C.codigo
      JOIN Financeiro.S009_Reqrecursos D ON A.dir_id_codigo = D.dir_id_codigo
    `,
  selecionaConta: `
      SELECT A.*, B.AGE_DESCRICAO
      FROM Financeiro.S009_Conta A
      JOIN Comum.S000_Agencia B ON A.AGE_ID_NUMERO = B.AGE_ID_NUMERO
      WHERE A.reg_id_codigo = :reg
    `,
  selecionaCaixa: `
    SELECT 
      A.CAI_ID_CODIGO, A.CAI_TIPO, A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO,
      A.DIR_ID_CODIGO, A.CAI_DATA, A.CAI_DOCUMENTO, A.CAI_DESCRICAO, A.CAI_VALOR,
      A.FPA_ID_CODIGO, A.CH_ID_CODIGO, A.BAN_ID_CODIGO, A.CAI_SALDOANT, A.TDE_ID_CODIGO,
      A.PRA_ID_CODIGO, A.CCX_ID_CODIGO, A.CAI_OPERADOR, A.CAI_NCHEQUE,
      B.FPA_DESCRICAO, D.Tde_Descricao, e.ban_cheque, A.CAI_DTDEPOSITO
    FROM 
      Financeiro.S009_Caixa A
      JOIN Financeiro.S009_FormaPagamento B ON A.FPA_ID_CODIGO = B.FPA_ID_CODIGO
      LEFT JOIN Financeiro.S009_Reqrecursos C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO
      LEFT JOIN Financeiro.S009_TIPODESP D ON A.Tde_Id_Codigo = d.tde_id_codigo
      LEFT JOIN Financeiro.S009_Banco E ON A.Ban_Id_Codigo = e.ban_id_codigo
  `,

  selecionaBanco: `
    SELECT 
      A.ELE_ID_CODIGO, A.BAN_ID_CODIGO, A.BAN_TIPO, A.BAN_DATA, A.BAN_DOCUMENTO,
      A.BAN_DESCRICAO, A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO,
      A.FPA_ID_CODIGO, ROUND(A.BAN_VALOR, 2) AS BAN_VALOR, A.BAN_CONFIRMA, 
      A.BAN_DTCONFIRMA, A.BAN_CHEQUE, ROUND(A.BAN_SALDOANT, 2) AS BAN_SALDOANT,
      A.CON_ID_CODIGO, A.BAN_ID_NUMERO, A.AGE_ID_NUMERO, A.CON_CONTA, A.FPA_DESCRICAO, 
      A.TDE_DESCRICAO, A.TDE_ID_CODIGO, A.PRA_ID_CODIGO, B.CCB_ID_CODIGO, C.AGE_DESCRICAO
    FROM 
      Financeiro.V009_Banco A
      JOIN Financeiro.S009_Banco B ON A.BAN_ID_CODIGO = B.BAN_ID_CODIGO
      JOIN Comum.S000_Agencia C ON A.AGE_ID_NUMERO = C.AGE_ID_NUMERO
  `,

  selecionaRespConta: `
    SELECT 
      B.CODCOLIGADA, B.CHAPA, B.CON_DTINICIO, B.CON_DTFIM, B.CON_ATIVO,
      B.CON_ID_CODIGO, B.RES_ID_CODIGO, C.Nome, D.Descricao, E.CPF
    FROM 
      Financeiro.S009_Conta A
      JOIN Financeiro.S009_RESPCONTA B ON A.CON_ID_CODIGO = B.CON_ID_CODIGO
      JOIN RM.Pfunc C ON B.CHAPA = C.CHAPA
      JOIN Rm.Psecao D ON C.CODSECAO = D.CODIGO
      JOIN Rm.Ppessoa E ON C.CODPESSOA = E.CODIGO
  `,

  selecionaElemento: `
    SELECT 
      B.CON_ID_CODIGO, B.TDE_ID_CODIGO, B.ELE_ID_CODIGO, C.TDE_DESCRICAO
    FROM 
      Financeiro.S009_Conta A
      JOIN Financeiro.S009_ELEMENTO B ON A.CON_ID_CODIGO = B.CON_ID_CODIGO
      JOIN Financeiro.S009_TIPODESP C ON B.TDE_ID_CODIGO = C.TDE_ID_CODIGO
  `,

  selecionaReembolso: `
    SELECT 
      A.*, B.FPA_ID_CODIGO, B.SQE_DTSAQUE, B.SQE_VLPREST,
      B.SQE_DTPREST, B.SQE_VLSAQUE, B.SQE_TIPOSAQUE,
      B.SQE_EFETIVO, B.SQE_DTPEDIDO
    FROM 
      Financeiro.S009_Reembolso A
      JOIN Financeiro.S009_Saque B ON A.SQE_ID_CODIGO = B.SQE_ID_CODIGO
  `,

  selecionaTotalDocumento: `
    SELECT 
      A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.ITE_ID_CODIGO, A.SQE_ID_CODIGO, A.REE_DATA,
      A.REE_AUTORIZADO, A.RRE_JUSTIFICATIVA, A.RRE_SAQUE,
      B.PCO_ID_CODIGO, B.NDO_DATA, B.NDO_ID_NUMERO, C.PES_NOME
    FROM 
      Financeiro.V009_TotalDoc A
      JOIN Financeiro.S009_NDOCUMENTO B ON A.NDO_ID_CODIGO = B.NDO_ID_CODIGO
      JOIN COMUM.S000_Pessoa C ON B.PES_ID_CODIGO = C.PES_ID_CODIGO
  `,

  selecionaJustificativa: `
    SELECT 
      A.JUS_ID_CODIGO, A.ORI_ID_CODIGO, A.DTC_ID_ITEM, A.NDO_ID_CODIGO,
      A.PCO_ID_CODIGO, A.JUS_DESCRICAO
    FROM 
      Financeiro.S009_Justificativa A
      JOIN Financeiro.S009_Detalhedoc B ON A.DTC_ID_ITEM = B.DTC_ID_ITEM
  `,

  selecionaEstorno: `
    SELECT 
      A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.PCO_ID_CODIGO,
      A.FPA_ID_CODIGO, A.EXT_VALOR, A.EXT_DATA, A.CHAPA, A.NOME, A.CODIGO, A.DESCRICAO, A.EXT_JUSTIFICA,
      A.TDE_ID_CODIGO, A.TDE_DESCRICAO, B.IRR_VALOR_SOL, B.IRR_VALOR_CONC, B.IRR_VALOR_PREST, C.SQE_TIPOSAQUE
    FROM 
      Financeiro.V009_Estorno A
      JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
      JOIN Financeiro.S009_Saque C ON A.SQE_ID_CODIGO = C.SQE_ID_CODIGO
  `,
  selecionaDocPContasNum: `
    SELECT DIR_ID_CODIGO, SQE_ID_CODIGO, NDO_ID_CODIGO, PCO_ID_CODIGO, PES_ID_CODIGO,
           PES_PESSOA, NDO_ID_NUMERO, NDO_DATA, NDO_DTENTREGA, NDO_OPERADOR, STS_ID_CODIGO,
           PES_NOME, CHAPA, NOME, CODIGO, DESCRICAO, VALORTOTAL, SQE_DTPREST,
           tDE_DESCRICAO, TDE_ID_CODIGO, SQE_VLSAQUE, SQE_VLPREST, SQE_DTSAQUE,
           PCO_TIPO, PCO_TOTDOC, PRA_ID_CODIGO, REQ_ID_CODIGO, SQE_EFETIVO, REG_ID_CODIGO
    FROM Financeiro.v009_DocPContasNum
  `,

  selecionaDocPContasRec: `
    SELECT A.DIR_ID_CODIGO, A.SQE_ID_CODIGO, A.SQE_DTPREST, A.CHAPA, A.NOME, A.CODIGO, A.DESCRICAO,
           A.NDO_ID_CODIGO, A.PCO_ID_CODIGO, A.PES_ID_CODIGO, A.PES_PESSOA, A.NDO_ID_NUMERO,
           A.NDO_DATA, A.NDO_DTENTREGA, A.STS_ID_CODIGO, A.NDO_OPERADOR, A.PES_NOME, A.VALORTOTAL,
           A.TDE_ID_CODIGO, A.SQE_VLSAQUE, A.SQE_VLPREST, A.PCO_TIPO, A.PCO_TOTDOC, A.PRA_ID_CODIGO,
           A.SQE_EFETIVO, B.TDE_DESCRICAO, A.REG_ID_CODIGO
    FROM Financeiro.V009_Docpcontasrec A
    JOIN Financeiro.S009_TIPODESP B ON A.TDE_ID_CODIGO = B.TDE_ID_CODIGO
    WHERE A.REG_ID_CODIGO = :REG
  `,

  selecionaDocPrestContas: `
    SELECT NDO_ID_NUMERO, NDO_DATA, NDO_DTENTREGA, PES_NOME, DTC_ID_ITEM,
           NDO_ID_CODIGO, PCO_ID_CODIGO, DES_ID_CODIGO, DTC_DESCRICAO, TDE_ID_CODIGO,
           DTC_CODDETALHE, DTC_VALOR, DTC_QTDADE, UN_SIGLA, DTC_VLTOTAL, DTC_VALORDOC,
           UN_DESCRICAO, TDE_DESCRICAO, PCO_TIPO, PCO_TOTDOC
    FROM Financeiro.V009_DOCPRESTCONTAS
  `,

  selecionaItensTransf: `
    SELECT A.ITF_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.CHAPA,
           A.CODCOLIGADA, A.ITF_VALOR, A.ITF_DATA, A.ITF_JUSTIFICA, A.ITF_AUTORIZADO,
           B.NOME, B.DESCRICAO, B.TDE_DESCRICAO,
           C.NOME, D.DESCRICAO, B.PRA_ID_CODIGO, B.CHAPA, B.TDE_ID_CODIGO
    FROM Financeiro.S009_ITENSTRANSF A
    JOIN Financeiro.v009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
    JOIN RM.PFUNC C ON A.CHAPA = C.CHAPA
    JOIN RM.PSECAO D ON C.CODSECAO = D.CODIGO
  `,

  selecionaSaqueFunc: `
    SELECT A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.CHAPA, A.TDE_ID_CODIGO,
           A.VALORSAQUE, B.TDE_DESCRICAO
    FROM Financeiro.V009_SALDO A
    JOIN Financeiro.S009_TIPODESP B ON A.TDE_ID_CODIGO = B.TDE_ID_CODIGO
  `,

  selecionaConcedeFunc: `
    SELECT A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.CHAPA, A.ITE_ID_CODIGO,
           A.VALORCON, A.VALORSOL, A.TDE_ID_CODIGO, B.TDE_DESCRICAO
    FROM Financeiro.V009_CONCEDE A
    JOIN Financeiro.S009_TIPODESP B ON A.TDE_ID_CODIGO = B.TDE_ID_CODIGO
  `,

  selecionaSaldoDesp: `
    SELECT A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.CHAPA, A.TDE_ID_CODIGO, A.VALORSAQUE,
           B.VALORCON, C.TDE_DESCRICAO
    FROM Financeiro.V009_Saldo A
    JOIN Financeiro.V009_Concede B ON A.CHAPA = B.CHAPA AND A.TDE_ID_CODIGO = B.TDE_ID_CODIGO
    JOIN Financeiro.S009_TipoDesp C ON A.TDE_ID_CODIGO = C.TDE_ID_CODIGO
  `,
  selecionaSaldo: `
  Select * From Financeiro.V009_Saldo
  Where RRE_ID_CODIGO=:CODREQ and CHAPA=:CODFUN and TDE_ID_CODIGO=7
`,

  selecionaSaqueViagem: `
    SELECT A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.FPA_ID_CODIGO,
           A.SQE_DTSAQUE, A.SQE_VLPREST, A.SQE_DTPREST, A.SQE_VLSAQUE, A.SQE_TIPOSAQUE,
           A.SQE_EFETIVO, A.SQE_DTPEDIDO, A.SQE_LOTE, A.SQE_ANOLOTE, A.SQE_EMPENHO,
           B.REQ_ID_CODIGO, D.TDE_DESCRICAO, D.TDE_ID_CODIGO
    FROM Financeiro.S009_Saque A
    JOIN Financeiro.S009_ReqNumerario B ON A.RRE_ID_CODIGO = B.RRE_ID_CODIGO
    JOIN TRANSPORTE.S001_REQUISICAO C ON C.REQ_ID_CODIGO = B.REQ_ID_CODIGO
    JOIN Financeiro.S009_TIPODESP D ON E.TDE_ID_CODIGO = D.TDE_ID_CODIGO
    JOIN Financeiro.S009_ITENSREQREC E ON A.RRE_ID_CODIGO = E.RRE_ID_CODIGO AND A.ITE_ID_CODIGO = E.ITE_ID_CODIGO
  `,
  selecionaExtPrestContasAdian: `
  SELECT DTC_ID_ITEM, DTC_CODDETALHE, DTC_DESCRICAO, DTC_QTDADE, UN_SIGLA,
         DTC_VALOR, DTC_VLTOTAL, NDO_DATA, NDO_ID_CODIGO, NDO_ID_NUMERO,
         NDO_DTENTREGA, DES_DESCRICAO, PES_NOME, PES_TIPO, PES_ID_CODIGO,
         PES_PESSOA, NOMEPESSOA, DOCUMENTO,
         PCO_ID_CODIGO, PCO_TIPO, PCO_TOTDOC, CHAPA, CODSECAO, NOME,
         FPA_DESCRICAO, SQE_ID_CODIGO, ITE_ID_CODIGO, RRE_ID_CODIGO,
         DIR_ID_CODIGO, FPA_ID_CODIGO, SQE_DTSAQUE, SQE_VLPREST, SQE_DTPREST,
         SQE_VLSAQUE, SQE_TIPOSAQUE, SQE_EFETIVO, SQE_DTPEDIDO, SQE_LOTE,
         SQE_ANOLOTE, JUS_DESCRICAO, ndo_titulo, ndo_serie
  FROM Financeiro.v009_ExtPContasAdian A
`,
  selecionaPContas: `
  SELECT A.PCO_ID_CODIGO, A.PCO_TIPO, A.PCO_TOTDOC
  FROM Financeiro.S009_PContas A
`,
  selecionaDetalheDoc: `
  SELECT A.DTC_ID_ITEM, A.NDO_ID_CODIGO, A.PCO_ID_CODIGO, A.DES_ID_CODIGO, A.DTC_DESCRICAO,
         A.TDE_ID_CODIGO, A.DTC_CODDETALHE, A.DTC_VALOR, A.DTC_QTDADE, A.UN_SIGLA, A.DTC_VLTOTAL,
         A.DTC_VALORDOC, B.TDE_DESCRICAO, C.UN_DESCRICAO
  FROM Financeiro.S009_DetalheDoc A, Financeiro.S009_TipoDesp B, Financeiro.S009_Unidade C
  WHERE A.TDE_ID_CODIGO = B.TDE_ID_CODIGO AND
        A.UN_SIGLA = C.UN_SIGLA
`,
  selecionaNumDocumento: `
  SELECT A.NDO_ID_CODIGO, A.PCO_ID_CODIGO, A.PES_ID_CODIGO, A.PES_PESSOA, A.NDO_ID_NUMERO,
         A.NDO_DATA, A.NDO_DTENTREGA, A.NDO_OPERADOR, A.STS_ID_CODIGO, B.PES_NOME, 
         A.NDO_SERIE, A.NDO_TITULO
  FROM Financeiro.S009_NDocumento A, COMUM.S000_PESSOA B
  WHERE A.PES_ID_CODIGO = B.PES_ID_CODIGO AND
        A.PES_PESSOA = B.PES_PESSOA
`,
  selecionaPContasNum: `
  SELECT A.PCO_ID_CODIGO, A.RNU_ID_CODIGO, B.RNU_ID_CODIGO, B.SQE_ID_CODIGO,
         B.REQ_ID_CODIGO, B.ITE_ID_CODIGO, B.RRE_ID_CODIGO, B.DIR_ID_CODIGO,
         B.RNU_DTINICIO, B.RNU_HORAINICIO, B.RNU_DTFIM, B.RNU_HORAFIM, D.PRA_ID_CODIGO
  FROM Financeiro.S009_PContasNum A, Financeiro.S009_ReqNumerario B,
       Financeiro.S009_PContas C, Financeiro.S009_Reqrecursos D
  WHERE A.PCO_ID_CODIGO = C.PCO_ID_CODIGO AND
        C.PCO_TIPO = 'N' AND
        A.RNU_ID_CODIGO = B.RNU_ID_CODIGO AND
        B.RRE_ID_CODIGO = D.RRE_ID_CODIGO
`,
  selecionaReqNumerario: `
  SELECT A.RNU_ID_CODIGO, A.SQE_ID_CODIGO, A.REQ_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO,
         A.DIR_ID_CODIGO, A.RNU_DTINICIO, A.RNU_HORAINICIO, A.RNU_DTFIM, A.RNU_HORAFIM, C.CHAPA,
         A.RNU_MOTIVO, A.RNU_PACOTE, A.RNU_INTPREV, A.RNU_PARPREV, A.RNU_INTREAL, A.RNU_PARREAL,
         D.REQ_STATUS, D.TRA_ID_CODIGO, A.RNU_GOVERNADOR, A.RNU_VLINTEGRAL, A.RNU_VLPARCIAL, 
         A.RNU_VLBASE,
         CONCAT(CONCAT(A.RNU_DTINICIO, '  '), A.RNU_HORAINICIO) AS SAIDA,
         CONCAT(CONCAT(A.RNU_DTFIM, '  '), A.RNU_HORAFIM) AS RETORNO,
         (TO_DATE(CONCAT(CONCAT(NVL(A.RNU_DTFIM, '30/12/1899'), '  '), NVL(A.RNU_HORAFIM, '00:00')), 'DD/MM/YYYY HH24:Mi:ss') -
         TO_DATE(CONCAT(CONCAT(NVL(A.RNU_DTINICIO, '30/12/1899'), '  '), NVL(A.RNU_HORAINICIO, '10:00')), 'DD/MM/YYYY HH24:Mi:ss')) AS DIARIA
  FROM Financeiro.S009_ReqNumerario A, Financeiro.S009_Saque B, 
       Financeiro.S009_ITENSREQREC C, Transporte.S001_Requisicao D
  WHERE B.SQE_TIPOSAQUE = 'N' AND
        A.SQE_ID_CODIGO = B.SQE_ID_CODIGO AND
        B.ITE_ID_CODIGO = C.ITE_ID_CODIGO AND
        A.REQ_ID_CODIGO = D.REQ_ID_CODIGO
`,
  selecionaSaquePendente: `
  SELECT A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO,
         A.FPA_ID_CODIGO, A.SQE_DTSAQUE, A.SQE_VLPREST, A.SQE_DTPREST, A.SQE_VLSAQUE,
         A.SQE_TIPOSAQUE, A.SQE_EFETIVO, A.SQE_DTPEDIDO, A.SQE_EMPENHO,
         A.SQE_LOTE, A.SQE_ANOLOTE, A.STS_DESCRICAO, A.CHAPA, A.ORI_ID_CODIGO,
         A.PRA_INICIO_RECURSO, A.PRA_FIM_RECURSO, A.FPA_DESCRICAO, A.TDE_ID_CODIGO,
         A.NOME, A.DESCRICAO, A.PRA_ID_CODIGO, A.RRE_JUSTIFICATIVA, A.CODBANCOPAGTO,
         A.SQE_TERCEIRO, A.SQE_USUARIO, A.NOMEPESSOA,
         A.CODAGENCIAPAGTO, A.CONTAPAGAMENTO, B.TDE_DESCRICAO
  FROM Financeiro.V009_SaquePendente A, Financeiro.S009_TIPODESP B
  WHERE A.TDE_ID_CODIGO = B.TDE_ID_CODIGO
`,
  selecionaExtratoGeral: `
SELECT B.*, A.RRE_ID_CODIGO, A.AGS_VALOR_SOLIC, A.AGS_VALOR_CONC,
       A.AGS_VALOR_PREST, E.TDE_DESCRICAO, D.DESCRICAO
FROM Financeiro.S009_AGRUPARECURSO A
JOIN Financeiro.V009_EXTRATODIRETORIA B ON A.dir_id_codigo = B.dir_id_codigo
JOIN COMUM.S000_DIRETORIA C ON A.DIR_ID_CODIGO = C.DIR_ID_CODIGO
JOIN RM.PSECAO D ON C.CODIGO = D.CODIGO
JOIN Financeiro.S009_TIPODESP E ON A.TDE_ID_CODIGO = E.TDE_ID_CODIGO;
`,
  selecionaExtratoDiretoria: `
SELECT B.*, E.DESCRICAO, C.TDE_DESCRICAO,
       D.AG1_VALOR_SOL, D.AG1_VALOR_PREST, D.AG1_VALOR_CONC, D.rre_id_codigo
FROM COMUM.S000_SUBORDINA1 A
JOIN Financeiro.V009_EXTRATONIVEL1 B ON A.SB1_ID_CODIGO = B.SB1_ID_CODIGO
JOIN Financeiro.S009_TIPODESP C ON B.tde_id_codigo = C.tde_id_codigo
JOIN Financeiro.S009_AGRUPANIVEL1 D ON b.dir_id_codigo = D.DIR_ID_CODIGO
JOIN RM.PSECAO E ON A.codigo = D.ag1_secao AND A.CODIGO = E.CODIGO;
`,
  selecionaExtratoGerencia: `
SELECT DISTINCT(B.AG2_SECAO), B.RRE_ID_CODIGO,
       C.DESCRICAO, D.TDE_DESCRICAO, A.VALORSAQUE, A.VALORPREST
FROM Financeiro.V009_EXTRATOGERENCIA A
JOIN Financeiro.S009_AGRUPANIVEL2 B ON A.CODSECAO = B.AG2_SECAO
JOIN RM.PSECAO C ON A.CODSECAO = C.CODIGO
JOIN Financeiro.S009_TIPODESP D ON A.TDE_ID_CODIGO = D.TDE_ID_CODIGO;
`,
  selecionaPrestPendente: `
SELECT DISTINCT(a.sqe_id_codigo), A.*, B.CHAPA, D.STS_DESCRICAO, E.PRA_INICIO_RECURSO,
       E.PRA_FIM_RECURSO, F.FPA_DESCRICAO, G.TDE_DESCRICAO, G.TDE_ID_CODIGO, B.ORI_ID_CODIGO
FROM Financeiro.S009_Saque A
JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
JOIN Financeiro.S009_REQRECURSOS C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO
JOIN Financeiro.S009_STATUS D ON C.STS_ID_CODIGO = D.STS_ID_CODIGO
JOIN Financeiro.S009_PRAZOS E ON C.PRA_ID_CODIGO = E.PRA_ID_CODIGO
JOIN Financeiro.S009_FORMAPAGAMENTO F ON A.FPA_ID_CODIGO = F.FPA_ID_CODIGO
JOIN Financeiro.S009_TIPODESP G ON B.TDE_ID_CODIGO = G.TDE_ID_CODIGO
WHERE A.SQE_DTPREST IS NULL
  AND SQE_EFETIVO IN ('P', 'S', 'E')
  AND E.PRA_ATIVO <> 'N';
`,
  selecionaExtPrestContasNum: `
SELECT DTC_ID_ITEM, DTC_CODDETALHE, DTC_DESCRICAO, DTC_QTDADE, UN_SIGLA, UN_SIGLA,
       DTC_VALOR, DTC_VLTOTAL, NDO_DATA, NDO_ID_CODIGO, NDO_ID_NUMERO, NDO_DTENTREGA,
       DES_DESCRICAO, PES_NOME, PES_TIPO, NOMEPESSOA, DOCUMENTO, PES_ID_CODIGO, PCO_ID_CODIGO, PCO_TIPO,
       PCO_TOTDOC, CHAPA, CODSECAO, nome, fpa_descricao, sqe_id_codigo,
       ITE_ID_CODIGO, rre_id_codigo, dir_id_codigo, fpa_id_codigo, SQE_DTSAQUE,
       sqe_vlprest, SQE_DTPREST, SQE_VLSAQUE, SQE_TIPOSAQUE, Sqe_Efetivo, SQE_DTPEDIDO,
       sqe_lote, sqe_anolote, REQ_ID_CODIGO, TDE_DESCRICAO, CPF
FROM Financeiro.V009_ExtPContasNum;
`,
  selectSaque: `
SELECT A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.FPA_ID_CODIGO,
       A.SQE_DTSAQUE, A.SQE_VLPREST, A.SQE_DTPREST, A.SQE_VLSAQUE, A.SQE_TIPOSAQUE,
       A.SQE_EFETIVO, A.SQE_DTPEDIDO, A.SQE_LOTE, A.SQE_ANOLOTE, A.STS_ID_CODIGO, A.SQE_TERCEIRO,
       A.SQE_USUARIO, K.NOMEPESSOA, D.STS_DESCRICAO, B.CHAPA, B.ORI_ID_CODIGO, B.IRR_VALOR_SOL,
       B.IRR_VALOR_CONC, B.IRR_VALOR_PREST, E.PRA_INICIO_RECURSO, E.PRA_FIM_RECURSO,
       F.FPA_DESCRICAO, G.TDE_DESCRICAO, G.TDE_ID_CODIGO, H.CODSECAO,
       H.NOME, H.Codbancopagto, H.codagenciapagto, H.contapagamento, I.DESCRICAO,
       J.RRE_JUSTIFICATIVA, L.CPF, A.SQE_EMPENHO
FROM Financeiro.S009_Saque A
JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
JOIN Financeiro.S009_REQRECURSOS C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO
LEFT JOIN Financeiro.S009_STATUS D ON A.STS_ID_CODIGO = D.STS_ID_CODIGO
JOIN Financeiro.S009_PRAZOS E ON C.PRA_ID_CODIGO = E.PRA_ID_CODIGO
LEFT JOIN Financeiro.S009_FORMAPAGAMENTO F ON A.FPA_ID_CODIGO = F.FPA_ID_CODIGO
JOIN Financeiro.S009_TIPODESP G ON B.TDE_ID_CODIGO = G.TDE_ID_CODIGO
JOIN RM.PFUNC H ON B.CHAPA = H.CHAPA
JOIN RM.PSECAO I ON H.CODSECAO = I.CODIGO
LEFT JOIN Financeiro.S009_REEMBOLSO J ON A.SQE_ID_CODIGO = J.SQE_ID_CODIGO
LEFT JOIN Financeiro.V009_PESSOA K ON A.PES_ID_CODIGO = K.PES_ID_CODIGO
LEFT JOIN RM.PPESSOA L ON L.CODIGO = H.CODPESSOA;
`,
  selecionaSaqueSetor: `
    SELECT A.*, B.DESCRICAO
    FROM Financeiro.V009_SAQUESETOR A
    JOIN Financeiro.V001_DIRETORIA B
      ON A.DIR_ID_CODIGO = B.DIR_ID_CODIGO;
  `,

  selecionaSaqueDiaria: `
  SELECT A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.FPA_ID_CODIGO,
       A.SQE_DTSAQUE, A.SQE_VLPREST, A.SQE_DTPREST, A.SQE_VLSAQUE, A.SQE_TIPOSAQUE,
       A.SQE_EFETIVO, A.SQE_DTPEDIDO, A.SQE_LOTE, A.SQE_ANOLOTE, A.STS_ID_CODIGO, A.SQE_TERCEIRO,
       A.SQE_USUARIO, K.NOMEPESSOA, D.STS_DESCRICAO, B.CHAPA, B.ORI_ID_CODIGO, B.IRR_VALOR_SOL,
       B.IRR_VALOR_CONC, B.IRR_VALOR_PREST, E.PRA_INICIO_RECURSO, E.PRA_FIM_RECURSO,
       F.FPA_DESCRICAO, G.TDE_DESCRICAO, G.TDE_ID_CODIGO, H.CODSECAO,
       H.NOME, H.Codbancopagto, H.codagenciapagto, H.contapagamento, I.DESCRICAO,
       J.RRE_JUSTIFICATIVA, L.cpf, A.SQE_EMPENHO
FROM Financeiro.S009_Saque A
JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO 
                                   AND A.RRE_ID_CODIGO = B.RRE_ID_CODIGO 
                                   AND A.DIR_ID_CODIGO = B.DIR_ID_CODIGO
JOIN Financeiro.S009_REQRECURSOS C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO 
                                   AND A.DIR_ID_CODIGO = C.DIR_ID_CODIGO
LEFT JOIN Financeiro.S009_STATUS D ON A.STS_ID_CODIGO = D.STS_ID_CODIGO
JOIN Financeiro.S009_PRAZOS E ON C.PRA_ID_CODIGO = E.PRA_ID_CODIGO
LEFT JOIN Financeiro.S009_FORMAPAGAMENTO F ON A.FPA_ID_CODIGO = F.FPA_ID_CODIGO
JOIN Financeiro.S009_TIPODESP G ON B.TDE_ID_CODIGO = G.TDE_ID_CODIGO
JOIN RM.PFUNC H ON B.CHAPA = H.CHAPA
JOIN rm.ppessoa L ON L.CODIGO = H.CODPESSOA
JOIN RM.PSECAO I ON H.CODSECAO = I.CODIGO
LEFT JOIN Financeiro.S009_REEMBOLSO J ON A.SQE_ID_CODIGO = J.SQE_ID_CODIGO
LEFT JOIN Financeiro.V009_PESSOA K ON A.PES_ID_CODIGO = K.PES_ID_CODIGO
WHERE B.TDE_ID_CODIGO = 7;
  `,

  SelPlanejaPendente: `
    SELECT  A.REQ_ID_CODIGO, A.CHAPA, A.NOME, A.CODIGO, A.DESCRICAO, A.REQ_DTSAIDA, A.REQ_DTRET, B.REG_ID_CODIGO, B.REG_DESCRICAO
   FROM FINANCEIRO.V009_PLANEJAPENDENTE A, FINANCEIRO.V009_SETORREGIONAL B
   WHERE A.CODIGO = B.CODIGO
  `,
};
