export const SelecionaItensRecurso = `
SELECT A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.ORI_ID_CODIGO, A.FPA_ID_CODIGO,
       A.STS_ID_CODIGO, A.TDE_ID_CODIGO, A.CHAPA, A.CODCOLIGADA,
       A.IRR_VALOR_SOL, A.IRR_DATA_SOL, A.IRR_VALOR_CONC, A.IRR_DATA_CONC, A.IRR_VALOR_PREST,
       A.IRR_DATA_PREST, A.IRR_JUSTIFICA, A.IRR_RECURSO, A.IRR_VALOR_AUT,
       A.IRR_VLRECEBIDO, A.IRR_VLDEVOLUCAO, A.IRR_VLSAQUE, A.IRR_VLTRANSFERIDO, A.IRR_SALDO,
       A.NOME, A.CODSECAO, A.DESCRICAO, A.TDE_DESCRICAO, A.RRE_DATA,
       A.RRE_DATAFIMPROC, A.PRA_INICIO_RECURSO, A.PRA_FIM_RECURSO, A.IRR_COMPLEMENTO,
       A.PRA_ATIVO, A.PRA_ID_CODIGO, A.STS_DESCRICAO, B.DESCRICAO AS DIRETORIA, A.IRR_VLREGIONAL
FROM Financeiro.v009_ItensReqRec A
INNER JOIN Financeiro.v001_Diretoria B ON A.DIR_ID_CODIGO = B.DIR_ID_CODIGO`;

export const SelecionaItenFunc = `
and A.Chapa =:NChapa and A.RRE_ID_CODIGO=:NREQ
order by A.ITE_ID_CODIGO
`;

export const SelecionaItensFunc = `
and A.Chapa =:NChapa
order by A.ITE_ID_CODIGO
`;

export const SelecionaAgrupaRec = `
SELECT 
    A.*, 
    B.STS_DESCRICAO, 
    C.TDE_DESCRICAO, 
    D.CODIGO, 
    D.DESCRICAO
FROM 
    FINANCEIRO.S009_AGRUPARECURSO A
JOIN 
    FINANCEIRO.S009_STATUS B ON A.STS_ID_CODIGO = B.STS_ID_CODIGO
JOIN 
    FINANCEIRO.S009_TIPODESP C ON A.TDE_ID_CODIGO = C.TDE_ID_CODIGO
JOIN 
    COMUM.S000_DIRETORIA E ON A.DIR_ID_CODIGO = E.DIR_ID_CODIGO
JOIN 
    RM.PSECAO D ON E.CODIGO = D.CODIGO`;

