export const selecionaPrestPendente = `
SELECT DISTINCT(a.sqe_id_codigo), A.*, B.CHAPA, D.STS_DESCRICAO, E.PRA_INICIO_RECURSO,
E.PRA_FIM_RECURSO, F.FPA_DESCRICAO, G.TDE_DESCRICAO, G.TDE_ID_CODIGO, B.ORI_ID_CODIGO
FROM Financeiro.S009_Saque A
JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
JOIN Financeiro.S009_REQRECURSOS C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO
JOIN Financeiro.S009_STATUS D ON C.STS_ID_CODIGO = D.STS_ID_CODIGO
JOIN Financeiro.S009_PRAZOS E ON C.PRA_ID_CODIGO = E.PRA_ID_CODIGO
JOIN Financeiro.S009_FORMAPAGAMENTO F ON A.FPA_ID_CODIGO = F.FPA_ID_CODIGO
JOIN Financeiro.S009_TIPODESP G ON B.TDE_ID_CODIGO = G.TDE_ID_CODIGO
WHERE A.SQE_DTPREST IS NULL
AND SQE_EFETIVO IN ('P', 'S', 'E')
AND E.PRA_ATIVO <> 'N'
AND B.TDE_ID_CODIGO = 7
`;

export const selecionaDocPContasNum = `
SELECT DIR_ID_CODIGO, SQE_ID_CODIGO, NDO_ID_CODIGO, PCO_ID_CODIGO, PES_ID_CODIGO,
PES_PESSOA, NDO_ID_NUMERO, NDO_DATA, NDO_DTENTREGA, NDO_OPERADOR, STS_ID_CODIGO,
PES_NOME, CHAPA, NOME, CODIGO, DESCRICAO, VALORTOTAL, SQE_DTPREST,
tDE_DESCRICAO, TDE_ID_CODIGO, SQE_VLSAQUE, SQE_VLPREST, SQE_DTSAQUE,
PCO_TIPO, PCO_TOTDOC, PRA_ID_CODIGO, REQ_ID_CODIGO, SQE_EFETIVO, REG_ID_CODIGO
FROM Financeiro.v009_DocPContasNum
`;
export const selecionaDocPContasNumPorSqe_id_codigo = `
${selecionaDocPContasNum}
Where SQE_ID_CODIGO=:CODSAQUE
`;

export const selecionaPContas = `
  SELECT A.PCO_ID_CODIGO, A.PCO_TIPO, A.PCO_TOTDOC
  FROM Financeiro.S009_PContas A
`;
export const selecionaExtPrestContasNum = `
SELECT DTC_ID_ITEM, DTC_CODDETALHE, DTC_DESCRICAO, DTC_QTDADE, UN_SIGLA, UN_SIGLA,
       DTC_VALOR, DTC_VLTOTAL, NDO_DATA, NDO_ID_CODIGO, NDO_ID_NUMERO, NDO_DTENTREGA,
       DES_DESCRICAO, PES_NOME, PES_TIPO, NOMEPESSOA, DOCUMENTO, PES_ID_CODIGO, PCO_ID_CODIGO, PCO_TIPO,
       PCO_TOTDOC, CHAPA, CODSECAO, nome, fpa_descricao, sqe_id_codigo,
       ITE_ID_CODIGO, rre_id_codigo, dir_id_codigo, fpa_id_codigo, SQE_DTSAQUE,
       sqe_vlprest, SQE_DTPREST, SQE_VLSAQUE, SQE_TIPOSAQUE, Sqe_Efetivo, SQE_DTPEDIDO,
       sqe_lote, sqe_anolote, REQ_ID_CODIGO, TDE_DESCRICAO, CPF
FROM Financeiro.V009_ExtPContasNum
`;
