export const selecionaPrestPendente = `
SELECT DISTINCT(a.sqe_id_codigo), A.*, B.CHAPA, D.STS_DESCRICAO, E.PRA_INICIO_RECURSO,
E.PRA_FIM_RECURSO, F.FPA_DESCRICAO, G.TDE_DESCRICAO, G.TDE_ID_CODIGO, B.ORI_ID_CODIGO
FROM Financeiro.S009_Saque A
JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
JOIN Financeiro.S009_REQRECURSOS C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO
JOIN Financeiro.S009_STATUS D ON C.STS_ID_CODIGO = D.STS_ID_CODIGO
JOIN Financeiro.S009_PRAZOS E ON C.PRA_ID_CODIGO = E.PRA_ID_CODIGO
JOIN Financeiro.S009_FORMAPAGAMENTO F ON A.FPA_ID_CODIGO = F.FPA_ID_CODIGO
JOIN Financeiro.S009_TIPODESP G ON B.TDE_ID_CODIGO = G.TDE_ID_CODIGO
WHERE A.SQE_DTPREST IS NULL
AND SQE_EFETIVO IN ('P', 'S', 'E')
AND E.PRA_ATIVO <> 'N'
AND B.TDE_ID_CODIGO = 7
`

export const  selecionaDocPContasNum = `
SELECT DIR_ID_CODIGO, SQE_ID_CODIGO, NDO_ID_CODIGO, PCO_ID_CODIGO, PES_ID_CODIGO,
PES_PESSOA, NDO_ID_NUMERO, NDO_DATA, NDO_DTENTREGA, NDO_OPERADOR, STS_ID_CODIGO,
PES_NOME, CHAPA, NOME, CODIGO, DESCRICAO, VALORTOTAL, SQE_DTPREST,
tDE_DESCRICAO, TDE_ID_CODIGO, SQE_VLSAQUE, SQE_VLPREST, SQE_DTSAQUE,
PCO_TIPO, PCO_TOTDOC, PRA_ID_CODIGO, REQ_ID_CODIGO, SQE_EFETIVO, REG_ID_CODIGO
FROM Financeiro.v009_DocPContasNum
`