export const selecionaReqNumerario = `
  SELECT A.RNU_ID_CODIGO, A.SQE_ID_CODIGO, A.REQ_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO,
         A.DIR_ID_CODIGO, A.RNU_DTINICIO, A.RNU_HORAINICIO, A.RNU_DTFIM, A.RNU_HORAFIM, C.CHAPA,
         A.RNU_MOTIVO, A.RNU_PACOTE, A.RNU_INTPREV, A.RNU_PARPREV, A.RNU_INTREAL, A.RNU_PARREAL,
         D.REQ_STATUS, D.TRA_ID_CODIGO, A.RNU_GOVERNADOR, A.RNU_VLINTEGRAL, A.RNU_VLPARCIAL, 
         A.RNU_VLBASE        
  FROM Financeiro.S009_ReqNumerario A, Financeiro.S009_Saque B, 
       Financeiro.S009_ITENSREQREC C, Transporte.S001_Requisicao D
  WHERE B.SQE_TIPOSAQUE = 'N' AND
        A.SQE_ID_CODIGO = B.SQE_ID_CODIGO AND
        B.ITE_ID_CODIGO = C.ITE_ID_CODIGO AND
        A.REQ_ID_CODIGO = D.REQ_ID_CODIGO        
`