
export const selectSaque= `
SELECT A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO, A.FPA_ID_CODIGO,
       A.SQE_DTSAQUE, A.SQE_VLPREST, A.SQE_DTPREST, A.SQE_VLSAQUE, A.SQE_TIPOSAQUE,
       A.SQE_EFETIVO, A.SQE_DTPEDIDO, A.SQE_LOTE, A.SQE_ANOLOTE, A.STS_ID_CODIGO, A.SQE_TERCEIRO,
       A.SQE_USUARIO, K.NOMEPESSOA, D.STS_DESCRICAO, B.CHAPA, B.ORI_ID_CODIGO, B.IRR_VALOR_SOL,
       B.IRR_VALOR_CONC, B.IRR_VALOR_PREST, E.PRA_INICIO_RECURSO, E.PRA_FIM_RECURSO,
       F.FPA_DESCRICAO, G.TDE_DESCRICAO, G.TDE_ID_CODIGO, H.CODSECAO,
       H.NOME, H.Codbancopagto, H.codagenciapagto, H.contapagamento, I.DESCRICAO,
       J.RRE_JUSTIFICATIVA, L.CPF, A.SQE_EMPENHO
FROM Financeiro.S009_Saque A
JOIN Financeiro.S009_ITENSREQREC B ON A.ITE_ID_CODIGO = B.ITE_ID_CODIGO
JOIN Financeiro.S009_REQRECURSOS C ON A.RRE_ID_CODIGO = C.RRE_ID_CODIGO
LEFT JOIN Financeiro.S009_STATUS D ON A.STS_ID_CODIGO = D.STS_ID_CODIGO
JOIN Financeiro.S009_PRAZOS E ON C.PRA_ID_CODIGO = E.PRA_ID_CODIGO
LEFT JOIN Financeiro.S009_FORMAPAGAMENTO F ON A.FPA_ID_CODIGO = F.FPA_ID_CODIGO
JOIN Financeiro.S009_TIPODESP G ON B.TDE_ID_CODIGO = G.TDE_ID_CODIGO
JOIN RM.PFUNC H ON B.CHAPA = H.CHAPA
JOIN RM.PSECAO I ON H.CODSECAO = I.CODIGO
LEFT JOIN Financeiro.S009_REEMBOLSO J ON A.SQE_ID_CODIGO = J.SQE_ID_CODIGO
LEFT JOIN Financeiro.V009_PESSOA K ON A.PES_ID_CODIGO = K.PES_ID_CODIGO
LEFT JOIN RM.PPESSOA L ON L.CODIGO = H.CODPESSOA
`
export const selecionaSaquePendente = `
SELECT A.SQE_ID_CODIGO, A.ITE_ID_CODIGO, A.RRE_ID_CODIGO, A.DIR_ID_CODIGO,
       A.FPA_ID_CODIGO, A.SQE_DTSAQUE, A.SQE_VLPREST, A.SQE_DTPREST, A.SQE_VLSAQUE,
       A.SQE_TIPOSAQUE, A.SQE_EFETIVO, A.SQE_DTPEDIDO, A.SQE_EMPENHO,
       A.SQE_LOTE, A.SQE_ANOLOTE, A.STS_DESCRICAO, A.CHAPA, A.ORI_ID_CODIGO,
       A.PRA_INICIO_RECURSO, A.PRA_FIM_RECURSO, A.FPA_DESCRICAO, A.TDE_ID_CODIGO,
       A.NOME, A.DESCRICAO, A.PRA_ID_CODIGO, A.RRE_JUSTIFICATIVA, A.CODBANCOPAGTO,
       A.SQE_TERCEIRO, A.SQE_USUARIO, A.NOMEPESSOA,
       A.CODAGENCIAPAGTO, A.CONTAPAGAMENTO, B.TDE_DESCRICAO
FROM Financeiro.V009_SaquePendente A, Financeiro.S009_TIPODESP B
WHERE A.TDE_ID_CODIGO = B.TDE_ID_CODIGO
`;

export const SelecionaPendencias = `
and A.Chapa =:NChapa`;
export const SelecionaPendencia = `
and A.Chapa =:NChapa and A.RRE_ID_CODIGO=:NREQ`;

export const SelecionaPendenciaPrest = `
And A.SQE_VLPREST=Null
and A.RRE_ID_CODIGO=:CODREQ and B.CHAPA=:CODFUN
`

