const combinacoes = [
  { SQE_TIPOSAQUE: 'N', SQE_EFETIVO: 'A', TIPO: 'Viagem', EFETUADO: 'Não - Aguardar Pagamento' },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'A',
    TIPO: 'Adiantamento',
    EFETUADO: 'Não - Retirar Pagamento na Tesouraria',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'C',
    TIPO: 'Adiantam.-Complemento',
    EFETUADO: 'Não - Retirar Pagamento na Tesouraria',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'C',
    TIPO: 'Viagem-Complemento',
    EFETUADO: 'Não - Aguardar Pagamento',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'R',
    TIPO: 'Despesas-Reembolso',
    EFETUADO: 'Não - Aguardando documentos/relatório para efetuar Pagamento',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'R',
    TIPO: 'Viagem-Reembolso',
    EFETUADO: 'Não - Aguardando documentos/relatório para efetuar Pagamento',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'D',
    TIPO: 'Despesas-c/Lanc.Documentos ',
    EFETUADO: 'Não - Aguardando documentos/relatório para efetuar Pagamento',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'D',
    TIPO: 'Viagem-c/Lanc. Documentos',
    EFETUADO: 'Não - Aguardando documentos/relatório para efetuar Pagamento',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'P',
    TIPO: 'Despesas-Reembolso ',
    EFETUADO: 'Sim - Pagamento Efetuado',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'P',
    TIPO: 'Viagem-Reembolso',
    EFETUADO: 'Sim - Pagamento Efetuado',
  },
  { SQE_TIPOSAQUE: 'N', SQE_EFETIVO: 'S', TIPO: 'Viagem', EFETUADO: 'Sim  - Pagamento Efetuado' },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'S',
    TIPO: 'Despesas Adiant.',
    EFETUADO: 'Sim - Pagamento Efetuado',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'E',
    TIPO: 'Viagem - Complemento',
    EFETUADO: 'Sim - Pagamento Efetuado',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'E',
    TIPO: 'Despesas Adian.- Compl',
    EFETUADO: 'Sim - Pagamento Efetuado',
  },
  { SQE_TIPOSAQUE: 'N', SQE_EFETIVO: 'X', TIPO: 'Viagem', EFETUADO: 'Estorno' },
  { SQE_TIPOSAQUE: 'R', SQE_EFETIVO: 'X', TIPO: 'Despesas Adiantamento', EFETUADO: 'Estorno' },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'G',
    TIPO: 'Viagem',
    EFETUADO: 'Autorização Cancelamento pelo Financeiro',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'G',
    TIPO: 'Despesas Adian.',
    EFETUADO: 'Autorização Cancelamento pelo Financeiro',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'Y',
    TIPO: 'Viagem',
    EFETUADO: 'Cancelamento efetuado pelo Financeiro',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'Y',
    TIPO: 'Despesas Adian.',
    EFETUADO: 'Cancelamento efetuado pelo Financeiro',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'F',
    TIPO: 'Despesas Adian.',
    EFETUADO: 'Aguardando Transferência para Reembolso',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'V',
    TIPO: 'Despesas Adian.',
    EFETUADO: 'Aguardando Transferência para Complemento',
  },
  {
    SQE_TIPOSAQUE: 'R',
    SQE_EFETIVO: 'T',
    TIPO: 'Despesas Adian.',
    EFETUADO: 'Aguardando Transferência para saque',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'T',
    TIPO: 'Viagem',
    EFETUADO: 'Aguardando Transferência para saque',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'V',
    TIPO: 'Viagem',
    EFETUADO: 'Aguardando Transferência para Complemento',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'F',
    TIPO: 'Viagem',
    EFETUADO: 'Aguardando Transferência para Reembolso',
  },
  {
    SQE_TIPOSAQUE: 'N',
    SQE_EFETIVO: 'B',
    TIPO: 'Viagem',
    EFETUADO: 'Aguardando Transferência para Complemento-Reembolso',
  },
];
