import { reqtransEntity } from 'src/database/db_oracle/entities/requisicaoTrans.entity';

export const mockreqtrans = {
  REQ_ID_CODIGO: 1,
  REG_ID_CODIGO: 7,
  COD_MUNICIP: 355030,
  TRA_ID_CODIGO: 1,
  REQ_DTREQ: '27/11/2002 11:32:46',
  REQ_DTSAIDA: new Date('2002-02-18'),
  REQ_MOTORISTA: 'N',
  REQ_HSAIDA: '11:00',
  REQ_DTRET: new Date('2002-02-18'),
  REQ_MOTIVO: null,
  REQ_HRET: '11:30',
  REQ_KM: 100,
  REQ_STATUS: 'FINALIZADA',
  REQ_DIARIA: null,
  REQ_INTEGRAL: null,
  REQ_PARCIAL: null,
  REQ_ESPECIAL: null,
  REQ_PACOTE: '1',
  REQ_GOVERNADOR: null,
};

export const mockreqtransCancelada = {
  COD_MUNICIP: 355030,
  REG_ID_CODIGO: 7,
  REQ_DIARIA: null,
  REQ_DTREQ: '27/11/2002 11:32:46',
  REQ_DTRET: new Date('2002-02-18'),
  REQ_DTSAIDA: new Date('2002-02-18'),
  REQ_ESPECIAL: null,
  REQ_GOVERNADOR: null,
  REQ_HRET: '11:30',
  REQ_HSAIDA: '11:00',
  REQ_ID_CODIGO: 1,
  REQ_INTEGRAL: null,
  REQ_KM: 100,
  REQ_MOTIVO: null,
  REQ_MOTORISTA: 'N',
  REQ_PACOTE: '1',
  REQ_PARCIAL: null,
  REQ_STATUS: 'CANCELADA',
  TRA_ID_CODIGO: 1,
};
